# Build, test and package idunno.Authentication nuget packages

trigger:
- master
- rel/*

pr:
- master
- rel/*

variables:
  solution: '**/*.sln'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    steps:
    # Setup Root CA for tests
    - task: PowerShell@2
      displayName: 'Setup Test Certificate Authority'
      inputs:
        filePath: installTestRootCA.ps1

    - task: UseDotNet@2
      displayName: 'Install .NET Core 3.x SDK'
      inputs:
        packageType: 'sdk'

    - task: UseDotNet@2
      displayName: 'Install .NET Core 2.x Runtime'
      inputs:
        version: '2.2.x'
        packageType: runtime

    # Build
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    # Test and publish test results
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        projects: '**/test/**/*.csproj'
        arguments: '--no-build --no-restore --logger trx --configuration $(buildConfiguration) --collect:"Code coverage" -- RunConfiguration.DisableAppDomain=true'

    # Create nuget packages
    - task: DotNetCoreCLI@2
      displayName: "dotnet pack"
      inputs:
        command: 'pack'
        arguments: '--configuration $(buildConfiguration) /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)'
        verbosityPack: minimal
        packagesToPack: '**/src/**/*.csproj'
        nobuild: true

    # Publish packages
    - publish: $(Build.ArtifactStagingDirectory)
      displayName: Publish artifacts
      artifact: BuildPackages
